# Generated by Django 3.1.6 on 2021-02-09 01:15

from django.db import migrations, models
from private_storage.fields import PrivateFileField

import bifrost.models.files


class Migration(migrations.Migration):

    dependencies = [("bifrost", "0003_delete_stubmodel")]

    operations = [
        migrations.CreateModel(
            name="BifrostFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=bifrost.models.files.generate_key, max_length=40
                    ),
                ),
                ("file", PrivateFileField()),
            ],
        )
    ]
