# Generated by Django 3.1.7 on 2021-02-26 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('bifrost', '0004_bifrostfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropperSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropper_endpoint', models.CharField(choices=[('P', 'https://dropper.snek.at/graphql'), ('L', 'http://localhost:8000/graphql')], default='P', max_length=6)),
                ('license', models.TextField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
